//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_U375
    {
        public int Label_ID { get; set; }
        public string Sequence { get; set; }
        public string Kanban { get; set; }
        public string OHC { get; set; }
        public string Map_Lamp { get; set; }
        public string Dome_Lamp { get; set; }
        public string Wire { get; set; }
        public string Antenna { get; set; }
        public string Remote { get; set; }
        public string C_date { get; set; }
        public string C_shift { get; set; }
        public string type { get; set; }
    }
}
