//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_FORD
    {
        public string ID { get; set; }
        public string Kanban { get; set; }
        public string Model { get; set; }
        public string Wire { get; set; }
        public string Mic { get; set; }
        public string LampFR1 { get; set; }
        public string LampFR2 { get; set; }
        public string LampRR { get; set; }
        public string Sunvisor_Driver { get; set; }
        public string Sunvisor_Passenger { get; set; }
        public string Remote { get; set; }
        public string Date_Time { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
