//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_P375
    {
        public string ID { get; set; }
        public string Kanban { get; set; }
        public string Label_PD { get; set; }
        public string Lamp_OHC { get; set; }
        public string Remote { get; set; }
        public string Wire { get; set; }
        public string Date_Time { get; set; }
        public string Type { get; set; }
    }
}
