//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_List
    {
        public string id_part { get; set; }
        public string A_PN { get; set; }
        public string N_PN { get; set; }
        public string Code { get; set; }
        public Nullable<int> s_mic { get; set; }
    }
}
