//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bom_t6
    {
        public string part_id { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string LAMP_OHC { get; set; }
        public string Remote { get; set; }
        public string Wire { get; set; }
        public string LAMP_OHC_2 { get; set; }
        public string LAMP_OHC_3 { get; set; }
        public string Last_UPDATE { get; set; }
        public Nullable<int> s_alert { get; set; }
        public string Comment { get; set; }
        public string barcode { get; set; }
        public Nullable<int> s_mod { get; set; }
        public Nullable<int> s_wire { get; set; }
    }
}
