//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bom_ford1
    {
        public string bom_id { get; set; }
        public string Model { get; set; }
        public string Wire { get; set; }
        public string Mic { get; set; }
        public string LAMPFR1 { get; set; }
        public string LAMPFR2 { get; set; }
        public string LAMPRR { get; set; }
        public string svr_driver { get; set; }
        public string svr_passenger { get; set; }
        public string Remote_code { get; set; }
        public string Last_Update { get; set; }
        public int Qty { get; set; }
    }
}
