//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bom_u375
    {
        public string bom_id { get; set; }
        public string u_ohc { get; set; }
        public string u_map_lamp { get; set; }
        public string u_dome_lamp { get; set; }
        public string u_wire { get; set; }
        public string u_remote { get; set; }
        public string u_atana { get; set; }
    }
}
