//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cf_part
    {
        public string id_cf_part { get; set; }
        public string date_cf { get; set; }
        public string supp_cf { get; set; }
        public string trm_cf { get; set; }
        public string n_pn_cf { get; set; }
        public string vin_cf { get; set; }
        public string part_no_cf { get; set; }
        public Nullable<int> s_cf { get; set; }
        public string kb_no_cf { get; set; }
        public string tra_cf { get; set; }
        public string EcssDate { get; set; }
        public Nullable<int> s_bom { get; set; }
        public string dateTrans { get; set; }
        public Nullable<int> s_st { get; set; }
        public Nullable<int> s_rw { get; set; }
        public string id_st { get; set; }
        public string id_rw { get; set; }
        public string date_s { get; set; }
        public Nullable<int> s_chk { get; set; }
    }
}
