//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_st_u375
    {
        public int ID_ST_U { get; set; }
        public string SEQ { get; set; }
        public string PN_F { get; set; }
        public string PN_N { get; set; }
        public string DT_CF { get; set; }
        public string DT_FG { get; set; }
        public Nullable<int> S_PD { get; set; }
        public Nullable<int> S_CF { get; set; }
        public Nullable<int> S_S { get; set; }
        public string Sequence { get; set; }
        public string Date_Sequence { get; set; }
    }
}
