//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_st_part
    {
        public string id_st_part { get; set; }
        public string date_st { get; set; }
        public string trm_st { get; set; }
        public string n_pn_st { get; set; }
        public string f_pn_st { get; set; }
        public Nullable<int> s_st { get; set; }
        public int s_st_o { get; set; }
        public string date_st_o { get; set; }
        public int s_st_rw { get; set; }
        public string id_st_rw { get; set; }
        public Nullable<int> s_st_chk { get; set; }
        public string Comment { get; set; }
        public string Label_ID { get; set; }
    }
}
