//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFordTran
    {
        public string DateRecv { get; set; }
        public string Header { get; set; }
        public string Suppliers { get; set; }
        public string Model { get; set; }
        public string EcssDate { get; set; }
        public string TrmRotation { get; set; }
        public string VIN { get; set; }
        public string PntName { get; set; }
        public string InitColor { get; set; }
        public string IpColor { get; set; }
        public string Base { get; set; }
        public string PartNo { get; set; }
        public string Footer1 { get; set; }
        public Nullable<int> bcPrint { get; set; }
    }
}
