//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRackLbl
    {
        public string RackID { get; set; }
        public string Lowest { get; set; }
        public string Highest { get; set; }
        public int No { get; set; }
    }
}
