//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApp.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSoap", Namespace="http://tempuri.org/")]
    public partial class WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_show_bomOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_find_bomOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_stockOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_stock_FGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS() {
            this.Url = global::WebApp.Properties.Settings.Default.WebApp_WebReference_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event U375_show_bomCompletedEventHandler U375_show_bomCompleted;
        
        /// <remarks/>
        public event U375_find_bomCompletedEventHandler U375_find_bomCompleted;
        
        /// <remarks/>
        public event U375_stockCompletedEventHandler U375_stockCompleted;
        
        /// <remarks/>
        public event U375_stock_FGCompletedEventHandler U375_stock_FGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_show_bom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_bom_u375[] U375_show_bom() {
            object[] results = this.Invoke("U375_show_bom", new object[0]);
            return ((tb_bom_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_show_bomAsync() {
            this.U375_show_bomAsync(null);
        }
        
        /// <remarks/>
        public void U375_show_bomAsync(object userState) {
            if ((this.U375_show_bomOperationCompleted == null)) {
                this.U375_show_bomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_show_bomOperationCompleted);
            }
            this.InvokeAsync("U375_show_bom", new object[0], this.U375_show_bomOperationCompleted, userState);
        }
        
        private void OnU375_show_bomOperationCompleted(object arg) {
            if ((this.U375_show_bomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_show_bomCompleted(this, new U375_show_bomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_find_bom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_bom_u375[] U375_find_bom(string id) {
            object[] results = this.Invoke("U375_find_bom", new object[] {
                        id});
            return ((tb_bom_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_find_bomAsync(string id) {
            this.U375_find_bomAsync(id, null);
        }
        
        /// <remarks/>
        public void U375_find_bomAsync(string id, object userState) {
            if ((this.U375_find_bomOperationCompleted == null)) {
                this.U375_find_bomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_find_bomOperationCompleted);
            }
            this.InvokeAsync("U375_find_bom", new object[] {
                        id}, this.U375_find_bomOperationCompleted, userState);
        }
        
        private void OnU375_find_bomOperationCompleted(object arg) {
            if ((this.U375_find_bomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_find_bomCompleted(this, new U375_find_bomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_stock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_st_u375[] U375_stock(string _date) {
            object[] results = this.Invoke("U375_stock", new object[] {
                        _date});
            return ((tb_st_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_stockAsync(string _date) {
            this.U375_stockAsync(_date, null);
        }
        
        /// <remarks/>
        public void U375_stockAsync(string _date, object userState) {
            if ((this.U375_stockOperationCompleted == null)) {
                this.U375_stockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_stockOperationCompleted);
            }
            this.InvokeAsync("U375_stock", new object[] {
                        _date}, this.U375_stockOperationCompleted, userState);
        }
        
        private void OnU375_stockOperationCompleted(object arg) {
            if ((this.U375_stockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_stockCompleted(this, new U375_stockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_stock_FG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_st_u375[] U375_stock_FG(string _date) {
            object[] results = this.Invoke("U375_stock_FG", new object[] {
                        _date});
            return ((tb_st_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_stock_FGAsync(string _date) {
            this.U375_stock_FGAsync(_date, null);
        }
        
        /// <remarks/>
        public void U375_stock_FGAsync(string _date, object userState) {
            if ((this.U375_stock_FGOperationCompleted == null)) {
                this.U375_stock_FGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_stock_FGOperationCompleted);
            }
            this.InvokeAsync("U375_stock_FG", new object[] {
                        _date}, this.U375_stock_FGOperationCompleted, userState);
        }
        
        private void OnU375_stock_FGOperationCompleted(object arg) {
            if ((this.U375_stock_FGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_stock_FGCompleted(this, new U375_stock_FGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_bom_u375 {
        
        private string bom_idField;
        
        private string u_ohcField;
        
        private string u_map_lampField;
        
        private string u_dome_lampField;
        
        private string u_wireField;
        
        private string u_remoteField;
        
        private string u_atanaField;
        
        /// <remarks/>
        public string bom_id {
            get {
                return this.bom_idField;
            }
            set {
                this.bom_idField = value;
            }
        }
        
        /// <remarks/>
        public string u_ohc {
            get {
                return this.u_ohcField;
            }
            set {
                this.u_ohcField = value;
            }
        }
        
        /// <remarks/>
        public string u_map_lamp {
            get {
                return this.u_map_lampField;
            }
            set {
                this.u_map_lampField = value;
            }
        }
        
        /// <remarks/>
        public string u_dome_lamp {
            get {
                return this.u_dome_lampField;
            }
            set {
                this.u_dome_lampField = value;
            }
        }
        
        /// <remarks/>
        public string u_wire {
            get {
                return this.u_wireField;
            }
            set {
                this.u_wireField = value;
            }
        }
        
        /// <remarks/>
        public string u_remote {
            get {
                return this.u_remoteField;
            }
            set {
                this.u_remoteField = value;
            }
        }
        
        /// <remarks/>
        public string u_atana {
            get {
                return this.u_atanaField;
            }
            set {
                this.u_atanaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_st_u375 {
        
        private int iD_ST_UField;
        
        private string sEQField;
        
        private string pN_FField;
        
        private string pN_NField;
        
        private string dT_CFField;
        
        private string dT_FGField;
        
        private System.Nullable<int> s_PDField;
        
        private System.Nullable<int> s_CFField;
        
        private System.Nullable<int> s_SField;
        
        private string sequenceField;
        
        private string date_SequenceField;
        
        /// <remarks/>
        public int ID_ST_U {
            get {
                return this.iD_ST_UField;
            }
            set {
                this.iD_ST_UField = value;
            }
        }
        
        /// <remarks/>
        public string SEQ {
            get {
                return this.sEQField;
            }
            set {
                this.sEQField = value;
            }
        }
        
        /// <remarks/>
        public string PN_F {
            get {
                return this.pN_FField;
            }
            set {
                this.pN_FField = value;
            }
        }
        
        /// <remarks/>
        public string PN_N {
            get {
                return this.pN_NField;
            }
            set {
                this.pN_NField = value;
            }
        }
        
        /// <remarks/>
        public string DT_CF {
            get {
                return this.dT_CFField;
            }
            set {
                this.dT_CFField = value;
            }
        }
        
        /// <remarks/>
        public string DT_FG {
            get {
                return this.dT_FGField;
            }
            set {
                this.dT_FGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_PD {
            get {
                return this.s_PDField;
            }
            set {
                this.s_PDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_CF {
            get {
                return this.s_CFField;
            }
            set {
                this.s_CFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_S {
            get {
                return this.s_SField;
            }
            set {
                this.s_SField = value;
            }
        }
        
        /// <remarks/>
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string Date_Sequence {
            get {
                return this.date_SequenceField;
            }
            set {
                this.date_SequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_show_bomCompletedEventHandler(object sender, U375_show_bomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_show_bomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_show_bomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_bom_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_bom_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_find_bomCompletedEventHandler(object sender, U375_find_bomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_find_bomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_find_bomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_bom_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_bom_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_stockCompletedEventHandler(object sender, U375_stockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_stockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_stockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_st_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_st_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_stock_FGCompletedEventHandler(object sender, U375_stock_FGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_stock_FGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_stock_FGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_st_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_st_u375[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591