//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApp.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSoap", Namespace="http://tempuri.org/")]
    public partial class WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_show_bomOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_find_bomOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_stockOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_stock_FGOperationCompleted;
        
        private System.Threading.SendOrPostCallback U375_Finish_goodOperationCompleted;
        
        private System.Threading.SendOrPostCallback P375_Finish_goodOperationCompleted;
        
        private System.Threading.SendOrPostCallback FORD_Finish_goodOperationCompleted;
        
        private System.Threading.SendOrPostCallback FORD_show_orderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AAT_show_orderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS() {
            this.Url = global::WebApp.Properties.Settings.Default.WebApp_WebReference_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event U375_show_bomCompletedEventHandler U375_show_bomCompleted;
        
        /// <remarks/>
        public event U375_find_bomCompletedEventHandler U375_find_bomCompleted;
        
        /// <remarks/>
        public event U375_stockCompletedEventHandler U375_stockCompleted;
        
        /// <remarks/>
        public event U375_stock_FGCompletedEventHandler U375_stock_FGCompleted;
        
        /// <remarks/>
        public event U375_Finish_goodCompletedEventHandler U375_Finish_goodCompleted;
        
        /// <remarks/>
        public event P375_Finish_goodCompletedEventHandler P375_Finish_goodCompleted;
        
        /// <remarks/>
        public event FORD_Finish_goodCompletedEventHandler FORD_Finish_goodCompleted;
        
        /// <remarks/>
        public event FORD_show_orderCompletedEventHandler FORD_show_orderCompleted;
        
        /// <remarks/>
        public event AAT_show_orderCompletedEventHandler AAT_show_orderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_show_bom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_bom_u375[] U375_show_bom() {
            object[] results = this.Invoke("U375_show_bom", new object[0]);
            return ((tb_bom_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_show_bomAsync() {
            this.U375_show_bomAsync(null);
        }
        
        /// <remarks/>
        public void U375_show_bomAsync(object userState) {
            if ((this.U375_show_bomOperationCompleted == null)) {
                this.U375_show_bomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_show_bomOperationCompleted);
            }
            this.InvokeAsync("U375_show_bom", new object[0], this.U375_show_bomOperationCompleted, userState);
        }
        
        private void OnU375_show_bomOperationCompleted(object arg) {
            if ((this.U375_show_bomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_show_bomCompleted(this, new U375_show_bomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_find_bom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_bom_u375[] U375_find_bom(string id) {
            object[] results = this.Invoke("U375_find_bom", new object[] {
                        id});
            return ((tb_bom_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_find_bomAsync(string id) {
            this.U375_find_bomAsync(id, null);
        }
        
        /// <remarks/>
        public void U375_find_bomAsync(string id, object userState) {
            if ((this.U375_find_bomOperationCompleted == null)) {
                this.U375_find_bomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_find_bomOperationCompleted);
            }
            this.InvokeAsync("U375_find_bom", new object[] {
                        id}, this.U375_find_bomOperationCompleted, userState);
        }
        
        private void OnU375_find_bomOperationCompleted(object arg) {
            if ((this.U375_find_bomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_find_bomCompleted(this, new U375_find_bomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_stock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_st_u375[] U375_stock(string _date) {
            object[] results = this.Invoke("U375_stock", new object[] {
                        _date});
            return ((tb_st_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_stockAsync(string _date) {
            this.U375_stockAsync(_date, null);
        }
        
        /// <remarks/>
        public void U375_stockAsync(string _date, object userState) {
            if ((this.U375_stockOperationCompleted == null)) {
                this.U375_stockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_stockOperationCompleted);
            }
            this.InvokeAsync("U375_stock", new object[] {
                        _date}, this.U375_stockOperationCompleted, userState);
        }
        
        private void OnU375_stockOperationCompleted(object arg) {
            if ((this.U375_stockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_stockCompleted(this, new U375_stockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_stock_FG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tb_st_u375[] U375_stock_FG(string _date) {
            object[] results = this.Invoke("U375_stock_FG", new object[] {
                        _date});
            return ((tb_st_u375[])(results[0]));
        }
        
        /// <remarks/>
        public void U375_stock_FGAsync(string _date) {
            this.U375_stock_FGAsync(_date, null);
        }
        
        /// <remarks/>
        public void U375_stock_FGAsync(string _date, object userState) {
            if ((this.U375_stock_FGOperationCompleted == null)) {
                this.U375_stock_FGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_stock_FGOperationCompleted);
            }
            this.InvokeAsync("U375_stock_FG", new object[] {
                        _date}, this.U375_stock_FGOperationCompleted, userState);
        }
        
        private void OnU375_stock_FGOperationCompleted(object arg) {
            if ((this.U375_stock_FGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_stock_FGCompleted(this, new U375_stock_FGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U375_Finish_good", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int U375_Finish_good() {
            object[] results = this.Invoke("U375_Finish_good", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void U375_Finish_goodAsync() {
            this.U375_Finish_goodAsync(null);
        }
        
        /// <remarks/>
        public void U375_Finish_goodAsync(object userState) {
            if ((this.U375_Finish_goodOperationCompleted == null)) {
                this.U375_Finish_goodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU375_Finish_goodOperationCompleted);
            }
            this.InvokeAsync("U375_Finish_good", new object[0], this.U375_Finish_goodOperationCompleted, userState);
        }
        
        private void OnU375_Finish_goodOperationCompleted(object arg) {
            if ((this.U375_Finish_goodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U375_Finish_goodCompleted(this, new U375_Finish_goodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P375_Finish_good", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int P375_Finish_good() {
            object[] results = this.Invoke("P375_Finish_good", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void P375_Finish_goodAsync() {
            this.P375_Finish_goodAsync(null);
        }
        
        /// <remarks/>
        public void P375_Finish_goodAsync(object userState) {
            if ((this.P375_Finish_goodOperationCompleted == null)) {
                this.P375_Finish_goodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP375_Finish_goodOperationCompleted);
            }
            this.InvokeAsync("P375_Finish_good", new object[0], this.P375_Finish_goodOperationCompleted, userState);
        }
        
        private void OnP375_Finish_goodOperationCompleted(object arg) {
            if ((this.P375_Finish_goodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P375_Finish_goodCompleted(this, new P375_Finish_goodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FORD_Finish_good", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FORD_Finish_good() {
            object[] results = this.Invoke("FORD_Finish_good", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FORD_Finish_goodAsync() {
            this.FORD_Finish_goodAsync(null);
        }
        
        /// <remarks/>
        public void FORD_Finish_goodAsync(object userState) {
            if ((this.FORD_Finish_goodOperationCompleted == null)) {
                this.FORD_Finish_goodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFORD_Finish_goodOperationCompleted);
            }
            this.InvokeAsync("FORD_Finish_good", new object[0], this.FORD_Finish_goodOperationCompleted, userState);
        }
        
        private void OnFORD_Finish_goodOperationCompleted(object arg) {
            if ((this.FORD_Finish_goodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FORD_Finish_goodCompleted(this, new FORD_Finish_goodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FORD_show_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CL_FORD_Order[] FORD_show_order(string _date) {
            object[] results = this.Invoke("FORD_show_order", new object[] {
                        _date});
            return ((CL_FORD_Order[])(results[0]));
        }
        
        /// <remarks/>
        public void FORD_show_orderAsync(string _date) {
            this.FORD_show_orderAsync(_date, null);
        }
        
        /// <remarks/>
        public void FORD_show_orderAsync(string _date, object userState) {
            if ((this.FORD_show_orderOperationCompleted == null)) {
                this.FORD_show_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFORD_show_orderOperationCompleted);
            }
            this.InvokeAsync("FORD_show_order", new object[] {
                        _date}, this.FORD_show_orderOperationCompleted, userState);
        }
        
        private void OnFORD_show_orderOperationCompleted(object arg) {
            if ((this.FORD_show_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FORD_show_orderCompleted(this, new FORD_show_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AAT_show_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CL_AAT_Order[] AAT_show_order(string _date) {
            object[] results = this.Invoke("AAT_show_order", new object[] {
                        _date});
            return ((CL_AAT_Order[])(results[0]));
        }
        
        /// <remarks/>
        public void AAT_show_orderAsync(string _date) {
            this.AAT_show_orderAsync(_date, null);
        }
        
        /// <remarks/>
        public void AAT_show_orderAsync(string _date, object userState) {
            if ((this.AAT_show_orderOperationCompleted == null)) {
                this.AAT_show_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAAT_show_orderOperationCompleted);
            }
            this.InvokeAsync("AAT_show_order", new object[] {
                        _date}, this.AAT_show_orderOperationCompleted, userState);
        }
        
        private void OnAAT_show_orderOperationCompleted(object arg) {
            if ((this.AAT_show_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AAT_show_orderCompleted(this, new AAT_show_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_bom_u375 {
        
        private string bom_idField;
        
        private string u_ohcField;
        
        private string u_map_lampField;
        
        private string u_dome_lampField;
        
        private string u_wireField;
        
        private string u_remoteField;
        
        private string u_atanaField;
        
        /// <remarks/>
        public string bom_id {
            get {
                return this.bom_idField;
            }
            set {
                this.bom_idField = value;
            }
        }
        
        /// <remarks/>
        public string u_ohc {
            get {
                return this.u_ohcField;
            }
            set {
                this.u_ohcField = value;
            }
        }
        
        /// <remarks/>
        public string u_map_lamp {
            get {
                return this.u_map_lampField;
            }
            set {
                this.u_map_lampField = value;
            }
        }
        
        /// <remarks/>
        public string u_dome_lamp {
            get {
                return this.u_dome_lampField;
            }
            set {
                this.u_dome_lampField = value;
            }
        }
        
        /// <remarks/>
        public string u_wire {
            get {
                return this.u_wireField;
            }
            set {
                this.u_wireField = value;
            }
        }
        
        /// <remarks/>
        public string u_remote {
            get {
                return this.u_remoteField;
            }
            set {
                this.u_remoteField = value;
            }
        }
        
        /// <remarks/>
        public string u_atana {
            get {
                return this.u_atanaField;
            }
            set {
                this.u_atanaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CL_AAT_Order {
        
        private string pLANTField;
        
        private string sUPPLField;
        
        private string lINEField;
        
        private string sCH_OFFField;
        
        private string tRIM_ONField;
        
        private string nHKA_CODEField;
        
        private string pART_NUMBERField;
        
        private string pAINTField;
        
        private string iNTERIORField;
        
        private string bRANDField;
        
        private string bASEField;
        
        private string vIN_NUMBERField;
        
        private string dATE_TIMEField;
        
        private System.Nullable<int> sTATUSField;
        
        /// <remarks/>
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        public string SUPPL {
            get {
                return this.sUPPLField;
            }
            set {
                this.sUPPLField = value;
            }
        }
        
        /// <remarks/>
        public string LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        public string SCH_OFF {
            get {
                return this.sCH_OFFField;
            }
            set {
                this.sCH_OFFField = value;
            }
        }
        
        /// <remarks/>
        public string TRIM_ON {
            get {
                return this.tRIM_ONField;
            }
            set {
                this.tRIM_ONField = value;
            }
        }
        
        /// <remarks/>
        public string NHKA_CODE {
            get {
                return this.nHKA_CODEField;
            }
            set {
                this.nHKA_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PART_NUMBER {
            get {
                return this.pART_NUMBERField;
            }
            set {
                this.pART_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string PAINT {
            get {
                return this.pAINTField;
            }
            set {
                this.pAINTField = value;
            }
        }
        
        /// <remarks/>
        public string INTERIOR {
            get {
                return this.iNTERIORField;
            }
            set {
                this.iNTERIORField = value;
            }
        }
        
        /// <remarks/>
        public string BRAND {
            get {
                return this.bRANDField;
            }
            set {
                this.bRANDField = value;
            }
        }
        
        /// <remarks/>
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
            }
        }
        
        /// <remarks/>
        public string VIN_NUMBER {
            get {
                return this.vIN_NUMBERField;
            }
            set {
                this.vIN_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string DATE_TIME {
            get {
                return this.dATE_TIMEField;
            }
            set {
                this.dATE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CL_FORD_Order {
        
        private string pLANTField;
        
        private string sUPPLField;
        
        private string lINEField;
        
        private string sCH_OFFField;
        
        private string tRIM_ONField;
        
        private string nHKA_CODEField;
        
        private string pART_NUMBERField;
        
        private string pAINTField;
        
        private string iNTERIORField;
        
        private string bRANDField;
        
        private string bASEField;
        
        private string vIN_NUMBERField;
        
        private string dATE_TIMEField;
        
        private System.Nullable<int> sTATUSField;
        
        /// <remarks/>
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        public string SUPPL {
            get {
                return this.sUPPLField;
            }
            set {
                this.sUPPLField = value;
            }
        }
        
        /// <remarks/>
        public string LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        public string SCH_OFF {
            get {
                return this.sCH_OFFField;
            }
            set {
                this.sCH_OFFField = value;
            }
        }
        
        /// <remarks/>
        public string TRIM_ON {
            get {
                return this.tRIM_ONField;
            }
            set {
                this.tRIM_ONField = value;
            }
        }
        
        /// <remarks/>
        public string NHKA_CODE {
            get {
                return this.nHKA_CODEField;
            }
            set {
                this.nHKA_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PART_NUMBER {
            get {
                return this.pART_NUMBERField;
            }
            set {
                this.pART_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string PAINT {
            get {
                return this.pAINTField;
            }
            set {
                this.pAINTField = value;
            }
        }
        
        /// <remarks/>
        public string INTERIOR {
            get {
                return this.iNTERIORField;
            }
            set {
                this.iNTERIORField = value;
            }
        }
        
        /// <remarks/>
        public string BRAND {
            get {
                return this.bRANDField;
            }
            set {
                this.bRANDField = value;
            }
        }
        
        /// <remarks/>
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
            }
        }
        
        /// <remarks/>
        public string VIN_NUMBER {
            get {
                return this.vIN_NUMBERField;
            }
            set {
                this.vIN_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string DATE_TIME {
            get {
                return this.dATE_TIMEField;
            }
            set {
                this.dATE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_st_u375 {
        
        private int iD_ST_UField;
        
        private string sEQField;
        
        private string pN_FField;
        
        private string pN_NField;
        
        private string dT_CFField;
        
        private string dT_FGField;
        
        private System.Nullable<int> s_PDField;
        
        private System.Nullable<int> s_CFField;
        
        private System.Nullable<int> s_SField;
        
        private string sequenceField;
        
        private string date_SequenceField;
        
        /// <remarks/>
        public int ID_ST_U {
            get {
                return this.iD_ST_UField;
            }
            set {
                this.iD_ST_UField = value;
            }
        }
        
        /// <remarks/>
        public string SEQ {
            get {
                return this.sEQField;
            }
            set {
                this.sEQField = value;
            }
        }
        
        /// <remarks/>
        public string PN_F {
            get {
                return this.pN_FField;
            }
            set {
                this.pN_FField = value;
            }
        }
        
        /// <remarks/>
        public string PN_N {
            get {
                return this.pN_NField;
            }
            set {
                this.pN_NField = value;
            }
        }
        
        /// <remarks/>
        public string DT_CF {
            get {
                return this.dT_CFField;
            }
            set {
                this.dT_CFField = value;
            }
        }
        
        /// <remarks/>
        public string DT_FG {
            get {
                return this.dT_FGField;
            }
            set {
                this.dT_FGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_PD {
            get {
                return this.s_PDField;
            }
            set {
                this.s_PDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_CF {
            get {
                return this.s_CFField;
            }
            set {
                this.s_CFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> S_S {
            get {
                return this.s_SField;
            }
            set {
                this.s_SField = value;
            }
        }
        
        /// <remarks/>
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string Date_Sequence {
            get {
                return this.date_SequenceField;
            }
            set {
                this.date_SequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_show_bomCompletedEventHandler(object sender, U375_show_bomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_show_bomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_show_bomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_bom_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_bom_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_find_bomCompletedEventHandler(object sender, U375_find_bomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_find_bomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_find_bomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_bom_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_bom_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_stockCompletedEventHandler(object sender, U375_stockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_stockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_stockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_st_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_st_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_stock_FGCompletedEventHandler(object sender, U375_stock_FGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_stock_FGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_stock_FGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tb_st_u375[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tb_st_u375[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void U375_Finish_goodCompletedEventHandler(object sender, U375_Finish_goodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U375_Finish_goodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U375_Finish_goodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void P375_Finish_goodCompletedEventHandler(object sender, P375_Finish_goodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P375_Finish_goodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P375_Finish_goodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FORD_Finish_goodCompletedEventHandler(object sender, FORD_Finish_goodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FORD_Finish_goodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FORD_Finish_goodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FORD_show_orderCompletedEventHandler(object sender, FORD_show_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FORD_show_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FORD_show_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CL_FORD_Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CL_FORD_Order[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AAT_show_orderCompletedEventHandler(object sender, AAT_show_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AAT_show_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AAT_show_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CL_AAT_Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CL_AAT_Order[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591